# Generated by Django 2.1.7 on 2019-03-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.IntegerField(unique=True)),
                ('password', models.TextField()),
                ('email_address', models.EmailField(max_length=254)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'USERS',
                'managed': False,
            },
        ),
    ]
