insert_listing = "INSERT INTO LISTING(HOST_ID,NAME, ROOM_TYPE, PROPERTY_TYPE, STREET, STATE, CITY, ZIP_CODE, AMENITIES, HOUST_RULES, DESCRIPTION, ACCOMMODATES, PICTURE_URL, CANCELLATION_POLICY,LATITUDE,LONGITUDE) VALUES(4608023, %s, %s, %s, %s, %s, %s, %s , %s,%s, %s, %s, %s, %s,'1.2','4.5')"

add_availability = "INSERT INTO AVAILABLE(AVAILABILITY_DATE, PRICE, IS_AVAILABLE) VALUES(TO_DATE(:1,'DD-MM-YY'), :2, :3)"
